version: "3.8"
services:
  core_postgresql:
    image: postgres:latest
    container_name: balkan-35C4n0r
    ports:
      - "5432:5432"

    volumes:
      - pg_data:/var/lib/postgresql/data

  goservice:
    environment:
      DB_HOST: "core_postgresql"
      DB_USER: "root"
      DB_PASSWORD: "password"
      DB_NAME: "bookstore"
      DB_PORT: "5432"
      SERVER_PORT: "8080"
      SERVER_SECRET: "ITS_NOT_A_BUG_ITS_A_FEATURE"
      ADMIN_SECRET: "SECRET_FOR_ADMIN"
      TIME_ZONE: "Asia/Kolkata"
    depends_on:
      - core_postgresql
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/certs
volumes:
  pg_data: